### ISSUE TITLE
Animated Textures are incorrectly converted

### ISSUE THREAD

**Issue by Krzyhau** [FEZModding/FEZRepacker#21]
It seems that when GIFs are converted back into AnimatedTexture, first frame is being used as a background for all of the following frames. I imagine it's caused by the recent massive refactor. 

Gomez, my boy, what happened to you?!
![obraz](https://github.com/FEZModding/FEZRepacker/assets/16310330/2075b3f6-f1b5-4219-bc27-c0d530c36190)

**Comment by Jenna1337** [comment]
I *think* the problem is in the `PopulateAtlasImageFromGif` method in `AnimatedTextureConverter.cs`, probably the `atlasImage.Frames.RootFrame`

**Comment by Krzyhau** [comment]
Okay, I figured this out. There's nothing wrong with conversion of GIFs into AnimatedTextures. Apparently Repacker was converting Animated Textures into GIFs that were "broken" in a way that could not be seen by most of software, most likely leading do undefined ImageSharp behavior.
