### ISSUE TITLE
can this unpack 3d assets in xnb format?

### ISSUE THREAD

**Issue by KittenOnCatnip** [FEZModding/FEZRepacker#23]
I am trying to mod a 3d game that uses XNA, I can't find anything that can do it.

```
> FEZRepacker.exe --convert-from-xnb ./alien.xnb ./output/

Converting 1 XNB files...
(1/1) ./alien.xnb
  Cannot deserialize XNB file: Additional XNB resources in a single file detected.. Saving raw file instead.
```

**Comment by Jenna1337** [comment]
As far as I can tell, XNA doesn't have a common structure for 3D models. Therefore, 3D models in XNA games are game engine specific, and seeing how FEZ uses its own custom 3D engine, it likely is not compatible with 3D assets for other games.
